version: '3.7'

services:
  postgres-9:
    container_name: postgres-9
    build: .
    restart: always
    volumes:
      - /docker/storage/storage-postgres-9:/var/lib/postgresql/data
    networks:
      - docker-net
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=PASSWORD-POSTGRES

networks:
  docker-net:
    external:
      name: docker-lan